package services

import (
	. "peterchu999/url-shorterner/dtos"
	"peterchu999/url-shorterner/model"
	repo "peterchu999/url-shorterner/repository"
	urlUtils "peterchu999/url-shorterner/utils/urls"
	"sync"
)

type URLService struct {
	sync.Mutex
}

var URLServiceObject *URLService

func createAutoGeneratedShortUrl(longUrl string) (string, error) {
	idx, err := repo.GetCurrentCount()

	if err != nil {
		return "", err
	}
	shortUrl := urlUtils.GenerateShortUrl(idx + 1)
	err = repo.CreateUrlData(model.URL{
		LongUrl:  longUrl,
		ShortUrl: shortUrl,
	})
	return shortUrl, err
}

func createCustomShortUrl(createShortUrlDto CreateShortUrlDto) (string, error) {
	err := repo.CreateCustomUrlData(model.URL{
		ShortUrl: createShortUrlDto.CustomShortUrl,
		LongUrl:  createShortUrlDto.LongUrl,
	})
	return createShortUrlDto.CustomShortUrl, err
}

func (us *URLService) CreateShortUrl(createShortUrlDto CreateShortUrlDto) (string, error) {
	us.Lock()
	defer us.Unlock()
	if createShortUrlDto.CustomShortUrl != "" {
		shortUrl, err := createCustomShortUrl(createShortUrlDto)
		return "/c/" + shortUrl, err
	}
	shortUrl, err := createAutoGeneratedShortUrl(createShortUrlDto.LongUrl)
	return "/t/" + shortUrl, err
}

func init() {
	URLServiceObject = &URLService{}
}
